working baseline
wraithe now does just a single task - create the .html files. soon,
we'll change it to just create a sqlite3 database, but for now, this is
it.

diff --git a/src/php/post2html b/src/php/post2html
--- a/src/php/post2html
+++ b/src/php/post2html
@@ -1,6 +1,6 @@
 #!/bin/bash
 ##************************************************************************
-## wraithe/tools/manifest
+## wraithe/bin/post2html
 ##
 ## Copyright (c) 2012 Michael D Henderson, all rights reserved
 ##
@@ -21,12 +21,20 @@
 ##
 ##************************************************************************
 
-while [ -n "${1}" ]
-do
-  [ "${1}" == all  -o "${1}" == --all  ] && find .   -type f
-  [ "${1}" == dir  -o "${1}" == --dir  ] && find src -type d
-  [ "${1}" == file -o "${1}" == --file ] && find src -type f
-  shift
-done | grep -v '.git' | sed -e 's/^\.$//' -e 's/^\.\///' -e '/^$/d' | sort -u
 
+for tgt in $( php -r "include 'bin/listArticles.php';" )
+do
+  echo " info: target is $tgt"
+
+  php -r "\$targetFile = '${tgt}'; include 'bin/outputArticle.php';" > "${tgt}"
+  retVal=$?
+  if [ ${retVal} != 0 ]
+  then
+    echo
+    echo "error: failed to compile templates"
+    echo
+    rm -f "${tgt}"
+    exit 2
+  fi
+done
 exit 0
diff --git a/tools/delete b/tools/delete
--- a/tools/delete
+++ b/tools/delete
@@ -1,9 +1,9 @@
 #!/bin/bash
-##************************************************************************
-## wraithe/tools/manifest
-##
-## Copyright (c) 2012 Michael D Henderson, all rights reserved
-##
+#*************************************************************************
+#* tools/delete
+#*
+#* Copyright (c) 2012 Michael D Henderson, all rights reserved
+#*
 ## This file is part of wraithe (http://github.com/quoha/wraithe).
 ##
 ## This program is free software: you can redistribute it and/or modify
@@ -21,12 +21,18 @@
 ##
 ##************************************************************************
 
+retVal=0
 while [ -n "${1}" ]
 do
-  [ "${1}" == all  -o "${1}" == --all  ] && find .   -type f
-  [ "${1}" == dir  -o "${1}" == --dir  ] && find src -type d
-  [ "${1}" == file -o "${1}" == --file ] && find src -type f
-  shift
-done | grep -v '.git' | sed -e 's/^\.$//' -e 's/^\.\///' -e '/^$/d' | sort -u
+  # if parm is a file, try to delete it
+  [ -f "${1}" ] && rm -f "${1}"
 
-exit 0
+  # if it still exists then report an error
+  if [ -e "${1}" ]
+  then
+    echo "error: unable to delete '${1}'"
+    retVal=2
+  fi
+  shift
+done
+exit $retVal
